language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

#  - "pypy3"
#
#matrix:
#  allow_failures:
#    - python: "pypy3"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgeographic-dev geographiclib-tools
  - sudo /usr/sbin/geographiclib-get-geoids minimal
  - sudo /usr/sbin/geographiclib-get-gravity minimal
  - sudo /usr/sbin/geographiclib-get-magnetic minimal

install:
  - pip install -r requirements-dev.txt
  - python setup.py build_ext --inplace

script:
  - python -m pytest -v --pyargs geomodels
