# $ make data
# $ env GEOGRAPHICLIB_DATA="$(pwd)/data" tox run
[tox]
minversion = 4.3.5
env_list =
    py310
    py311
    py312
    py313
    py314
    py314t
    coverage
    codestyle
    docs
isolated_build = True

[testenv]
description = run the tests with pytest
package = wheel
changedir = {envtmpdir}
dependency_groups =
    test
passenv = GEOGRAPHICLIB_DATA
commands =
    python3 -m pytest --doctest-modules {tty:--color=yes} -W error {posargs} --pyargs geomodels

[testenv:py314t]
basepython = python3.14t

[testenv:coverage]
description = run coverage
dependency_groups =
    coverage
changedir = {envtmpdir}
commands =
    python3 -m pytest {tty:--color=yes} --cov geomodels --cov-report=html --cov-report=term --pyargs geomodels

[testenv:codestyle]
description = run linting
allowlist_externals = ruff
skip_install = true
dependency_groups =
    lint
changedir = {package_root}
commands =
    python3 -m flake8 --count --statistics geomodels
    python3 -m pydocstyle --count geomodels
    python3 -m isort --check geomodels
    python3 -m black --check geomodels
    # python3 -m mypy --check-untyped-defs --ignore-missing-imports geomodels
    ruff check geomodels

[testenv:docs]
description = build docs
allowlist_externals = mkdir
changedir = docs
dependency_groups =
    docs
commands =
    mkdir -p _static
    python3 -m sphinx -W -b html . _build/html
    python3 -m sphinx -W -b doctest . _build/doctest
    python3 -m sphinx -W -b linkcheck . _build/linkcheck
    python3 -m sphinx -W -b spelling . _build/spelling
