name: Docs

on:
  push:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install docs dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install sphinx sphinxcontrib-spelling
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f requirements-docs.txt ]; then pip install -r requirements-docs.txt; fi

      - name: Build
        run: |
          python -m build

      - name: Install
        run: |
          python -m pip install dist/*.whl

      - name: Build docs
        run: |
          mkdir -p _static
          python3 -m sphinx -W -b html . _build/html
        working-directory: docs
        # env:
        #   PYTHONPATH: ..

      - name: Check links
        run: |
          mkdir -p _static
          python3 -m sphinx -W -b linkcheck . _build/linkcheck
        working-directory: docs
        # env:
        #   PYTHONPATH: ..

      - name: Doctest
        run: |
          geomodels-cli install-data -d ${GEOGRAPHICLIB_DATA} recommended
          mkdir -p _static
          python3 -m sphinx -W -b doctest . _build/doctest
        working-directory: docs
        env:
          GEOGRAPHICLIB_DATA: "../data"

      # - name: Spellcheck
      #   run: |
      #     mkdir -p _static
      #     python3 -m sphinx -W -b spelling . _build/spelling
      #   working-directory: docs
