name: Ubuntu

on:
  push:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

env:
  PACKAGE: geomodels

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install APT dependencies
        run: |
          sudo apt update
          sudo apt install libgeographic-dev

      - name: Install build dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip setuptools build
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Build package
        run: |
          python -m build
        env:
          GEOMODELS_IGNORE_BUNDLED_LIBS: TRUE
          GEOMODELS_GEOGRAPHICLIB_NAME: Geographic

      - name: Install
        run: |
          python -m pip install dist/*.whl

      - name: Prepare the environment
        run: |
          geomodels-cli install-data -d data recommended

      - name: Install test dependencies
        shell: bash
        run: |
          python -m pip install pytest pytest-cov
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi

      - name: Test CLI
        run: |
          geomodels-cli info

      - name: Test
        working-directory: dist
        run: |
          python -m pytest --pyargs ${PACKAGE}
        env:
          GEOGRAPHICLIB_DATA: "../data"
